# Generated by Django 4.2.6 on 2023-11-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='incident_photos/')),
                ('description', models.TextField()),
                ('datetime_reported', models.DateTimeField(auto_now_add=True)),
                ('narrative', models.TextField()),
            ],
            options={
                'ordering': ['-datetime_reported'],
            },
        ),
    ]
