# Generated by Django 4.2.6 on 2023-12-05 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incident_reports', '0002_incidentreport_latitude_incidentreport_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
