# Generated by Django 4.2.6 on 2023-12-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_reports', '0004_alter_incidentreport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
