# Generated by Django 4.2.6 on 2023-12-07 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident_reports', '0005_incidentreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('Middle_name', models.CharField(max_length=255)),
                ('affix_name', models.CharField(max_length=255)),
                ('civil_status', models.CharField(max_length=255)),
                ('birthdate', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=6)),
                ('contact_number', models.CharField(max_length=255)),
                ('citizenship', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('highesteducationattainment', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('incident_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victims', to='incident_reports.incidentreport')),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('Middle_name', models.CharField(max_length=255)),
                ('affix_name', models.CharField(max_length=255)),
                ('civil_status', models.CharField(max_length=255)),
                ('birthdate', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=6)),
                ('contact_number', models.CharField(max_length=255)),
                ('citizenship', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('waddress', models.CharField(max_length=255)),
                ('incident_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='incident_reports.incidentreport')),
            ],
        ),
        migrations.CreateModel(
            name='ChildConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('Middle_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=11)),
                ('homecontact_number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('incident_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_conflicts', to='incident_reports.incidentreport')),
            ],
        ),
    ]
