# Generated by Django 4.2.6 on 2023-12-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_reports', '0006_alter_incidentreport_status_victim_suspect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='is_user_victim',
            field=models.BooleanField(default=False),
        ),
    ]
