# Generated by Django 4.2.6 on 2024-01-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_reports', '0010_incidentreport_is_emergency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='incident_reports.incidentsubcategory'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
