# Generated by Django 4.2.6 on 2024-01-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_reports', '0011_remove_incidentreport_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='narrative',
            field=models.TextField(blank=True, null=True),
        ),
    ]
