# Generated by Django 4.2.6 on 2024-01-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_reports', '0012_alter_incidentreport_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childconflict',
            old_name='Middle_name',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='suspect',
            old_name='Middle_name',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='victim',
            old_name='Middle_name',
            new_name='middle_name',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='affix_name',
        ),
        migrations.AddField(
            model_name='childconflict',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='nickname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='occupation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
