# Generated by Django 4.2.6 on 2024-01-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_reports', '0013_rename_middle_name_childconflict_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
