# Generated by Django 5.0.1 on 2024-02-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_reports', '0017_alter_incidentreport_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='dispatched_personnel',
            field=models.ManyToManyField(blank=True, to='incident_reports.personnel'),
        ),
    ]
