# Generated by Django 4.2.6 on 2024-01-19 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidIDType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='User_ID',
        ),
        migrations.AddField(
            model_name='customuser',
            name='valid_id_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.valididtype'),
        ),
    ]
