# Generated by Django 5.0.1 on 2024-01-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_valididtype_remove_customuser_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='UserValid',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
